### ISSUE TITLE
Can't build happy

### ISSUE THREAD

**Issue by georgefst** [mobilehaskell/user-guide#6]
Running `arm-linux-gnueabihf-cabal new-update && arm-linux-gnueabihf-cabal new-install happy` (in a fresh container) results in `cabal: Failed to build happy-1.19.9. The failure occurred during the configure
step. The build process terminated with exit code 2`. Same with old-style commands. I'm a bit of a noob here and I haven't got much to go on. Fairly sure sysroot is set up correctly as I can compile and run a 'Hello World'.

**Comment by angerman** [comment]
@georgefst try adding `-v` to the invocation to get more output.

**Comment by georgefst** [comment]
Install log with -v:

[happyInstallLog.txt](https://github.com/mobilehaskell/user-guide/files/3161506/happyInstallLog.txt)

**Comment by angerman** [comment]
Can you provide `/root/.cabal/logs/ghc-8.4.0.20180109/happy-1.19.10-bbae312f75191a323278b5e5a8eb52cd28b4e102a5dd6045882b3b2d0ac1d596.log` as well?

**Comment by georgefst** [comment]
[happy-1.19.10-bbae312f75191a323278b5e5a8eb52cd28b4e102a5dd6045882b3b2d0ac1d596.log](https://github.com/mobilehaskell/user-guide/files/3167465/happy-1.19.10-bbae312f75191a323278b5e5a8eb52cd28b4e102a5dd6045882b3b2d0ac1d596.log)

(I didn't know that could be found there, so I've already learnt something today. Thanks.)

**Comment by angerman** [comment]
```
[1 of 1] Compiling Main             ( /tmp/cabal-install.-275/dist-newstyle/tmp/src-275/happy-1.19.10/dist/setup/setup.hs, /tmp/cabal-install.-275/dist-newstyle/tmp/src-275/happy-1.19.10/dist/setup/Main.o )
Linking /tmp/cabal-install.-275/dist-newstyle/tmp/src-275/happy-1.19.10/dist/setup/setup ...
/tmp/cabal-install.-275/dist-newstyle/tmp/src-275/happy-1.19.10/dist/setup/setup: 1: /tmp/cabal-install.-275/dist-newstyle/tmp/src-275/happy-1.19.10/dist/setup/setup: Syntax error: word unexpected (expecting ")")
```

Oh, ohh! you are tyring to cross compile `happy`. Seems like you'd need to change the `build-type`. See also jgm/zip-archive#54 for a similar issue.

**Comment by georgefst** [comment]
Thanks. On reflection, that's not actually what I originally set out to do. I have a `c2hs`-based project which I'm trying to port to the Pi, and I believe running `cabal new-build` caused the system to attempt to install `happy` because `c2hs` depends on it. The cross-compilation setup obviously complicated this...

I'm now attempting to build using the `.hs` file output by `c2hs` instead, rather than trying to do the full build process through `cabal` in the container. I'm having difficulties getting the linker to find the necessary `.so` file, but it's probably time I opened a separate issue about that...
